---

- name: MariaDB repo setup
  tags: [mariadb_repo]
  when: args.apt is defined
  vars:
    cmd: "curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s - --mariadb-server-version=mariadb-{{args.apt.version}}"
  #debug: var=cmd
  shell: "{{cmd}}"
  args:
    warn: no

- name: Apt install
  tags: [xnever ,mariadb_apt]
  when: args.install is defined
  apt:
    pkg:
    - mariadb-common
    - python3-pymysql 

