---

#Get database size:
#  SELECT table_schema AS "Database", ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS "Size (MB)" FROM information_schema.TABLES GROUP BY table_schema
#Get post with strange image (R2P)
#  SELECT * FROM `wp_posts` where guid like '%1f64c.png'

- name: Clean mysql table
  tags: ["{{clean_table}}"]
  block:
  - debug: var=clean_item
